#!/usr/bin/env python3
"""
Send Telegram alert for Industries tickers with daily move > +1%.
Reads from data/snapshot.json (already generated by refresh workflow).
Looks up full ETF name from Yahoo Finance.
"""

import json
import os
import sys
import urllib.request
import urllib.parse
from datetime import datetime, timezone

import yfinance as yf

TELEGRAM_TOKEN   = os.environ.get("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID")
THRESHOLD        = 1.0   # minimum daily % move to alert on
GROUP_NAME       = "Industries"

# Cache of ticker -> name so we only call Yahoo once per ticker
_name_cache = {}

def get_name(ticker):
    """Look up the full ETF/company name from Yahoo Finance."""
    if ticker in _name_cache:
        return _name_cache[ticker]
    try:
        info = yf.Ticker(ticker).info
        name = info.get("shortName") or info.get("longName") or ticker
    except Exception:
        name = ticker
    _name_cache[ticker] = name
    return name


def send_telegram(message):
    if not TELEGRAM_TOKEN or not TELEGRAM_CHAT_ID:
        print("ERROR: TELEGRAM_TOKEN or TELEGRAM_CHAT_ID not set.", file=sys.stderr)
        sys.exit(1)
    url  = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    data = urllib.parse.urlencode({
        "chat_id":    TELEGRAM_CHAT_ID,
        "text":       message,
        "parse_mode": "HTML",
    }).encode()
    req = urllib.request.Request(url, data=data, method="POST")
    with urllib.request.urlopen(req, timeout=10) as resp:
        result = json.loads(resp.read())
        if not result.get("ok"):
            print(f"Telegram error: {result}", file=sys.stderr)
            sys.exit(1)


def main():
    # Load snapshot
    try:
        with open("data/snapshot.json") as f:
            snapshot = json.load(f)
    except FileNotFoundError:
        print("ERROR: data/snapshot.json not found.", file=sys.stderr)
        sys.exit(1)

    groups = snapshot.get("groups", {})
    rows   = groups.get(GROUP_NAME, [])

    if not rows:
        print(f"No data found for group '{GROUP_NAME}'.")
        return

    # Filter tickers with daily > threshold
    movers = [r for r in rows if r.get("daily") is not None and r["daily"] >= THRESHOLD]

    # Sort by daily % descending
    movers.sort(key=lambda r: r["daily"], reverse=True)

    now_aest = datetime.now(timezone.utc).strftime("%d %b %Y")

    if not movers:
        message = (
            f"📊 <b>Market Alert — {now_aest}</b>\n\n"
            f"No {GROUP_NAME} tickers moved more than +{THRESHOLD}% yesterday."
        )
    else:
        lines = [f"📊 <b>Industries Movers &gt;+{THRESHOLD}% — {now_aest}</b>\n"]
        for r in movers:
            ticker = r.get("ticker", "?")
            name   = get_name(ticker)
            daily  = r["daily"]
            grade  = r.get("abc", "?")
            lines.append(f"<b>{ticker}</b> [{grade}]  +{daily:.2f}%  —  {name}")

        lines.append(f"\n<i>{len(movers)} ticker(s) above +{THRESHOLD}%</i>")
        message = "\n".join(lines)

    print(message)
    send_telegram(message)
    print("✓ Alert sent.")


if __name__ == "__main__":
    main()
